apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meerkat.fullname" . }}
  labels: {{- include "meerkat.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets: {{- toYaml . | nindent 2 }}
{{- end }}
